### ISSUE TITLE
Exclude nvidia-driver and other nvidia pkgs from unattended-upgrades

### ISSUE THREAD

**Issue by KasperSkytte** [aau-claaudia/aicloud#37]
Hi. Today you had aicloud go down because the nvidia-driver was automatically upgraded. On biocloud I do the following to avoid the trouble:

```
# usually named "50unattended-upgrade", but the number prefix can potentially vary
- name: Find unattended-upgrades apt config file
  find:
    paths: /etc/apt/apt.conf.d
    patterns: "*unattended-upgrade*"
    file_type: file
  register: unattended_upgrade_file

- name: Get the path to the unattended-upgrades config file (if found)
  set_fact:
    unattended_config_file: "{{ unattended_upgrade_file.files[0].path }}"
  when: unattended_upgrade_file.matched > 0

# https://github.com/mvo5/unattended-upgrades?tab=readme-ov-file#supported-options-reference
- name: Ensure NVIDIA packages are blacklisted in unattended-upgrades
  blockinfile:
    path: "{{ unattended_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - blacklist NVIDIA pkgs"
    insertafter: '^.*Unattended-Upgrade::Package-Blacklist.*$'
    block: |
      "nvidia-";
      "libnvidia-";
  when: unattended_upgrade_file.matched > 0
  ```
